// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relevantz.ExitManagement.Data.DBContexts;

#nullable disable

namespace Relevantz.ExitManagement.Data.Migrations
{
    [DbContext(typeof(ExitManagementDbContext))]
    [Migration("20260310114254_ClearanceItem")]
    partial class ClearanceItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.AssetDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ExitRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ExitRequestId", "AssetCode")
                        .HasDatabaseName("IX_AssetDeclaration_Request_Code");

                    b.ToTable("AssetDeclarations");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLog_Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.ClearanceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ExitRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("PendingDueAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExitRequestId", "DepartmentName", "ItemName")
                        .IsUnique()
                        .HasDatabaseName("UX_ClearanceItem_Request_Dept_Item");

                    b.ToTable("ClearanceItems");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("L1ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("L2ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Employee_Email");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Employee_EmployeeCode");

                    b.HasIndex("L1ManagerId");

                    b.HasIndex("L2ManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.ExitApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int>("ExitRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExitRequestId", "ApproverId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExitApproval_Request_Approver");

                    b.ToTable("ExitApprovals");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.ExitRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedLastWorkingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ClearanceCompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailedReason")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("HandoverBuddyId")
                        .HasColumnType("int");

                    b.Property<string>("HandoverNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("HrApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsKtCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KtRemarks")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("L1ApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("L2ApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoticePeriodDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProposedLastWorkingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ReasonType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RehireBlockedUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RehireDecision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RehireDecisionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RehireRemarks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("ResignationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<int>("RiskScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RiskSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("SettlementCompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SuccessorEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HandoverBuddyId");

                    b.HasIndex("SuccessorEmployeeId");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("IX_ExitRequest_Employee_Status");

                    b.ToTable("ExitRequests");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.KtTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompletionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ExitRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExitRequestId", "Title")
                        .IsUnique()
                        .HasDatabaseName("UX_KtTask_Request_Title");

                    b.ToTable("KtTasks");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("RecipientEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientEmployeeId", "IsRead")
                        .HasDatabaseName("IX_Notification_Recipient_Read");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Role_Name");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.AssetDeclaration", b =>
                {
                    b.HasOne("Relevantz.ExitManagement.Common.Entities.ExitRequest", "ExitRequest")
                        .WithMany("AssetDeclarations")
                        .HasForeignKey("ExitRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExitRequest");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.ClearanceItem", b =>
                {
                    b.HasOne("Relevantz.ExitManagement.Common.Entities.ExitRequest", "ExitRequest")
                        .WithMany()
                        .HasForeignKey("ExitRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExitRequest");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.Employee", b =>
                {
                    b.HasOne("Relevantz.ExitManagement.Common.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("L1ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relevantz.ExitManagement.Common.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("L2ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.ExitApproval", b =>
                {
                    b.HasOne("Relevantz.ExitManagement.Common.Entities.ExitRequest", "ExitRequest")
                        .WithMany("Approvals")
                        .HasForeignKey("ExitRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExitRequest");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.ExitRequest", b =>
                {
                    b.HasOne("Relevantz.ExitManagement.Common.Entities.Employee", "Employee")
                        .WithMany("ExitRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Relevantz.ExitManagement.Common.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("HandoverBuddyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Relevantz.ExitManagement.Common.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("SuccessorEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.KtTask", b =>
                {
                    b.HasOne("Relevantz.ExitManagement.Common.Entities.ExitRequest", "ExitRequest")
                        .WithMany("KtTasks")
                        .HasForeignKey("ExitRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExitRequest");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.Employee", b =>
                {
                    b.Navigation("ExitRequests");
                });

            modelBuilder.Entity("Relevantz.ExitManagement.Common.Entities.ExitRequest", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AssetDeclarations");

                    b.Navigation("KtTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
